### ISSUE TITLE
v8 deprecated functions and datatype mismatch 

### ISSUE THREAD

**Issue by BogdanStoenescu** [fireveined/node-simulate-native-click#2]
Hi there,
I need to make this project work and I get an error message in relation to some deprecated v8 functions plus data type mismatch.
Do you have any suggestions? What am I doing wrong?

agstoenescu@core-auto-app6 MINGW64 /c/Automation/Emails (EmailsYahooWindows)
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@12.18.4 | win32 | x64
gyp info find Python using Python version 3.8.6 found at "C:\Python38\python.exe"
gyp info find VS using VS2019 (16.7.30523.141) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\agstoenescu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Automation\\Emails\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\agstoenescu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\agstoenescu\\AppData\\Local\\node-gyp\\Cache\\12.18.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\agstoenescu\\AppData\\Local\\node-gyp\\Cache\\12.18.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\agstoenescu\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info              spawn args   '-Dnode_lib_file=C:\\\\Users\\\\agstoenescu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.18.4\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Automation\\Emails',
gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
gyp                     info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Automation\\Emails\\build',
gyp                     info spawn args   '-Goutput_dir=.'
gyp info                              spawn args ]
    gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info                                  spawn args   '/nologo',
    gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
    Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  main.cpp
  win_delay_load_hook.cc
C:\Automation\Emails\main.cpp(14,50): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' (compiling source file ..\main.cpp) [C:\Au
tomation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(15,34): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' (compiling source file ..\main.cpp) [C:\Au
tomation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(16,34): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' (compiling source file ..\main.cpp) [C:\Au
tomation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(73,45): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' (compiling source file ..\main.cpp) [C:\Au
tomation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(79,63): warning C4311: 'type cast': pointer truncation from 'HWND' to 'int' [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(79,63): warning C4302: 'type cast': truncation from 'HWND' to 'int' [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(84,50): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' (compiling source file ..\main.cpp) [C:\Au
tomation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(99,11): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(100,11): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(105,11): error C2065: 'Handle': undeclared identifier [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(105,18): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Automation\Emails\build\addon.vcxproj]
C:\Users\agstoenescu\AppData\Local\node-gyp\Cache\12.18.4\include\node\v8.h(3496): message : see declaration of 'v8::Object' [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(105,26): error C2065: 'exports': undeclared identifier [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(105,33): error C2182: 'Init': illegal use of type 'void' [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(106,1): error C2448: 'Init': function-style initializer appears to be a function definition [C:\Automation\Emails\build\addon.vcxproj]
C:\Automation\Emails\main.cpp(113,1): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Automation\Emails\build\addon.vcxproj]      
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit co
de: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\agstoenescu\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\agstoenescu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-g\node_modules\\node-gyp\\bin\\node-g
yp.js" "rebuild"
gyp ERR! cwd C:\Automation\Emails
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok

**Comment by fireveined** [comment]
The package was tested using node v9, you are using v12 and there was change in V8 API somewhere between. I'll take a look, it shouldn't be much work.

**Comment by BogdanStoenescu** [comment]
Thank you very much for your reply.

I look forward to hearing from you.

Bogdan

**Comment by Christian1984** [comment]
Hi @fireveined - Did you manage to get that fixed? I'd really like to use your package in a project. Plus, may I ask you to kindly add a permissive license to your project (ideally MIT, if you don't mind)? That would be lovely :-)
